export const images = [
  {
    id: 1,
    copy: 'Llama Marrón Sobre Campo De Hierba Verde Cerca De La Montaña',
    licencia: 'Uso gratuito',
    lugar: 'Aguas Calientes, Cusco, Peru',
    autor: 'Alex Azabache',
    thumbnail: 'https://images.pexels.com/photos/3879058/pexels-photo-3879058.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    url: 'https://www.pexels.com/es-es/foto/llama-marron-sobre-campo-de-hierba-verde-cerca-de-la-montana-3879058/',
  },
  {
    id: 2,
    copy: 'Mujer andina cargando una oveja bebé',
    licencia: 'Uso gratuito',
    lugar: 'Cuzco, Perú',
    autor: 'Rodolfo Clix',
    thumbnail: 'https://images.pexels.com/photos/3947398/pexels-photo-3947398.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    url: 'https://www.pexels.com/es-es/foto/animal-mascota-america-bufanda-3947398/',
  },
  {
    id: 3,
    copy: 'Mujer Sosteniendo Tabla De Surf',
    licencia: 'Uso gratuito',
    lugar: 'Trujillo - Huanchaco, Perú',
    autor: 'Molly Champion',
    thumbnail: 'https://images.pexels.com/photos/1822745/pexels-photo-1822745.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    url: 'https://www.pexels.com/es-es/foto/mujer-sosteniendo-tabla-de-surf-1822745/',
  },
  {
    id: 4,
    copy: 'Catedral de Cuzco - Iglesia principal de la ciudad',
    licencia: 'Uso gratuito',
    lugar: 'Cusco, Cuzco, Perú',
    autor: 'Gilmer Diaz Estela',
    thumbnail: 'https://images.pexels.com/photos/7616375/pexels-photo-7616375.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    url: 'https://www.pexels.com/es-es/foto/gente-punto-de-referencia-caminando-edificio-7616375/',
  },
  {
    id: 5,
    copy: 'Foto De Puerta Azul',
    licencia: 'Uso gratuito',
    lugar: 'Ciudad de Arequipa en Perú',
    autor: 'Chelsea Cook',
    thumbnail: 'https://images.pexels.com/photos/2929910/pexels-photo-2929910.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    url: 'https://www.pexels.com/es-es/foto/foto-de-puerta-azul-2929910/',
  },
];
